# basic options
title: Test site for BPM docu
author: Santa Upeniece
email: santa.upeniece@sap.com
description: Test site for BPM docu
baseurl: "/testestest"
url: "https://santa-test-factory.github.io"
permalink: date

# Configure the plugin here
category_path: "testestest/category" # <- default value
category_layout: "category_index.html" # <- default value
paginate: 2 # <- turn on pagination with two posts per page

# Build settings
markdown: kramdown
theme: minima
permalink: /:year/:month/:day/:title:output_ext
plugins:
    - jekyll-paginate
    - jekyll-category-pages
