# basic options
title: Test site for BPM docu
author: Santa Upeniece
email: santa.upeniece@sap.com
description: Test site for BPM docu
baseurl: "/testestest"
url: "https://santa-test-factory.github.io"
# header_pages:
#   - category/categories.html
#   - pages/process_definition/processdefinition.md
#   - pages/development/development.md
#   - pages/QA/qa.md
#   - pages/publishing/publishing.md
 
# Configure the plugin here
category_path: "testestest/category" # <- default value
category_layout: "category_index.html" # <- default value
paginate: 2 # <- turn on pagination with two posts per page

# Build settings
markdown: kramdown
theme: minima
permalink: /:year/:month/:day/:title:output_ext
plugins:
    - jekyll-paginate
    - jekyll-category-pages


github-username: Santa-test-factory
minima: 
  social-links:
    github: testestest

# This is from https://github.com/thinkshout/feeding-texas/blob/master/_config.yml
# Team directory used by the data_to_pages plugin.
location_dir: 'locations'
# contact_redirect: 'thanks'
tag_dir: 'blog/category'
# directory for csv data used to construct zip detail pages
# csv_dir: '_data'

# Blog pagination.
# paginate: 10
# paginate_path: "blog/page:num"
